#!/bin/bash

printf "Do you want to uninstall t2u-driver completely from your system? ('y'|'n')"

read input

case $input in
	'y')
	    sudo ifconfig ra0 down;
        sudo rm -rf /etc/Wireless/RT2870STA;
        sudo rm -rf /etc/Wireless/RT2860STA;
        sudo rmmod mt7650u_sta;
        # sudo rm /etc/sysconfig/network-scripts/ifcfg-ra0;
	    printf "Uninstalled. Please restart\n"
		;;
	'n')
	    printf "Nevermind. Bye!\n"
	    ;;
esac
exit 1
