cmd_/var/git-projects/archer-t2u-driver-install/files/os/linux/../../common/frq_cal.o := gcc -Wp,-MD,/var/git-projects/archer-t2u-driver-install/files/os/linux/../../common/.frq_cal.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/6/include  -I./arch/x86/include -I./arch/x86/include/generated/uapi -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -fno-pie -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -fno-pie -no-pie -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -Wno-frame-address -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -DCC_HAVE_ASM_GOTO -g -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -Wall -Wstrict-prototypes -Wno-trigraphs -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=mt7650u -DRESOURCE_PRE_ALLOC -DENHANCED_STAT_DISPLAY -I/var/git-projects/archer-t2u-driver-install/files/include -DDOT11_VHT_AC -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DDBG -DWPA_SUPPLICANT_SUPPORT -DNATIVE_WPA_SUPPLICANT_SUPPORT -DDOT11_N_SUPPORT -DDOT11N_DRAFT3 -DNEW_RATE_ADAPT_SUPPORT -DSTATS_COUNT_SUPPORT -DLED_CONTROL_SUPPORT -DRTMP_TEMPERATURE_TX_ALC -DMT76x0 -DRT65xx -DRLT_MAC -DRLT_RF -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DA_BAND_SUPPORT -DRTMP_EFUSE_SUPPORT -DNEW_MBSSID_MODE -DCONFIG_ANDES_SUPPORT -DMT7650 -DMT7630 -DMT7610  -DMODULE  -DKBUILD_BASENAME='"frq_cal"'  -DKBUILD_MODNAME='"mt7650u_sta"' -c -o /var/git-projects/archer-t2u-driver-install/files/os/linux/../../common/.tmp_frq_cal.o /var/git-projects/archer-t2u-driver-install/files/os/linux/../../common/frq_cal.c

source_/var/git-projects/archer-t2u-driver-install/files/os/linux/../../common/frq_cal.o := /var/git-projects/archer-t2u-driver-install/files/os/linux/../../common/frq_cal.c

deps_/var/git-projects/archer-t2u-driver-install/files/os/linux/../../common/frq_cal.o := \

/var/git-projects/archer-t2u-driver-install/files/os/linux/../../common/frq_cal.o: $(deps_/var/git-projects/archer-t2u-driver-install/files/os/linux/../../common/frq_cal.o)

$(deps_/var/git-projects/archer-t2u-driver-install/files/os/linux/../../common/frq_cal.o):
